<?php

namespace Database\Seeders;

use App\Models\Citys;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Citys::insert([
                ['id' => 1, 'nameCity' => 'Aïn Harrouda'],
                ['id' => 2, 'nameCity' => 'Ben Yakhlf'],
                ['id' => 3, 'nameCity' => 'Bouskoura'],
                ['id' => 4, 'nameCity' => 'Casablanca'],
                ['id' => 5, 'nameCity' => 'Médiouna'],
                ['id' => 6, 'nameCity' => 'Mohammadia'],
                ['id' => 7, 'nameCity' => 'Tit Mellil'],
                ['id' => 8, 'nameCity' => 'Ben Yakhlef'],
                ['id' => 9, 'nameCity' => 'Bejaâd'],
                ['id' => 10, 'nameCity' => 'Ben Ahmed'],
                ['id' => 11, 'nameCity' => 'Benslimane'],
                ['id' => 12, 'nameCity' => 'Berrechid'],
                ['id' => 13, 'nameCity' => 'Boujniba'],
                ['id' => 14, 'nameCity' => 'Boulanouare'],
                ['id' => 15, 'nameCity' => 'Bouznika'],
                ['id' => 16, 'nameCity' => 'Deroua'],
                ['id' => 17, 'nameCity' => 'El Borouj'],
                ['id' => 18, 'nameCity' => 'El Gara'],
                ['id' => 19, 'nameCity' => 'Guisser'],
                ['id' => 20, 'nameCity' => 'Hattane'],
                ['id' => 21, 'nameCity' => 'Khouribga'],
                ['id' => 22, 'nameCity' => 'Loulad'],
                ['id' => 23, 'nameCity' => 'Oued Zem'],
                ['id' => 24, 'nameCity' => 'Oulad Abbou'],
                ['id' => 25, 'nameCity' => 'Oulad HRiz Sahel'],
                ['id' => 26, 'nameCity' => 'Oulad Mrah'],
                ['id' => 27, 'nameCity' => 'Oulad Saïd'],
                ['id' => 28, 'nameCity' => 'Oulad Sidi Ben Daoud'],
                ['id' => 29, 'nameCity' => 'Ras El Aïn'],
                ['id' => 30, 'nameCity' => 'Settat'],
                ['id' => 31, 'nameCity' => 'Sidi Rahhal Chataï'],
                ['id' => 32, 'nameCity' => 'Soualem'],
                ['id' => 33, 'nameCity' => 'Azemmour'],
                ['id' => 34, 'nameCity' => 'Bir Jdid'],
                ['id' => 35, 'nameCity' => 'Bouguedra'],
                ['id' => 36, 'nameCity' => 'Echemmaia'],
                ['id' => 37, 'nameCity' => 'El Jadida'],
                ['id' => 38, 'nameCity' => 'Hrara'],
                ['id' => 39, 'nameCity' => 'Ighoud'],
                ['id' => 40, 'nameCity' => 'Jamâat Shaim'],
                ['id' => 41, 'nameCity' => 'Jorf Lasfar'],
                ['id' => 42, 'nameCity' => 'Khemis Zemamra'],
                ['id' => 43, 'nameCity' => 'Laaounate'],
                ['id' => 44, 'nameCity' => 'Moulay Abdallah'],
                ['id' => 45, 'nameCity' => 'Oualidia'],
                ['id' => 46, 'nameCity' => 'Oulad Amrane'],
                ['id' => 47, 'nameCity' => 'Oulad Frej'],
                ['id' => 48, 'nameCity' => 'Oulad Ghadbane'],
                ['id' => 49, 'nameCity' => 'Safi'],
                ['id' => 50, 'nameCity' => 'Sebt El Maârif'],
                ['id' => 51, 'nameCity' => 'Sebt Gzoula'],
                ['id' => 52, 'nameCity' => 'Sidi Ahmed'],
                ['id' => 53, 'nameCity' => 'Sidi Ali Ban Hamdouche'],
                ['id' => 54, 'nameCity' => 'Sidi Bennour'],
                ['id' => 55, 'nameCity' => 'Sidi Bouzid'],
                ['id' => 56, 'nameCity' => 'Sidi Smaïl'],
                ['id' => 57, 'nameCity' => 'Youssoufia'],
                ['id' => 58, 'nameCity' => 'Fès'],
                ['id' => 59, 'nameCity' => 'Aïn Cheggag'],
                ['id' => 60, 'nameCity' => 'Bhalil'],
                ['id' => 61, 'nameCity' => 'Boulemane'],
                ['id' => 62, 'nameCity' => 'El Menzel'],
                ['id' => 63, 'nameCity' => 'Guigou'],
                ['id' => 64, 'nameCity' => 'Imouzzer Kandar'],
                ['id' => 65, 'nameCity' => 'Imouzzer Marmoucha'],
                ['id' => 66, 'nameCity' => 'Missour'],
                ['id' => 67, 'nameCity' => 'Moulay Yaâcoub'],
                ['id' => 68, 'nameCity' => 'Ouled Tayeb'],
                ['id' => 69, 'nameCity' => 'Outat El Haj'],
                ['id' => 70, 'nameCity' => 'Ribate El Kheir'],
                ['id' => 71, 'nameCity' => 'Séfrou'],
                ['id' => 72, 'nameCity' => 'Skhinate'],
                ['id' => 73, 'nameCity' => 'Tafajight'],
                ['id' => 74, 'nameCity' => 'Arbaoua'],
                ['id' => 75, 'nameCity' => 'Aïn Dorij'],
                ['id' => 76, 'nameCity' => 'Dar Gueddari'],
                ['id' => 77, 'nameCity' => 'Had Kourt'],
                ['id' => 78, 'nameCity' => 'Jorf El Melha'],
                ['id' => 79, 'nameCity' => 'Kénitra'],
                ['id' => 80, 'nameCity' => 'Khenichet'],
                ['id' => 81, 'nameCity' => 'Lalla Mimouna'],
                ['id' => 82, 'nameCity' => 'Mechra Bel Ksiri'],
                ['id' => 83, 'nameCity' => 'Mehdia'],
                ['id' => 84, 'nameCity' => 'Moulay Bousselham'],
                ['id' => 85, 'nameCity' => 'Sidi Allal Tazi'],
                ['id' => 86, 'nameCity' => 'Sidi Kacem'],
                ['id' => 87, 'nameCity' => 'Sidi Slimane'],
                ['id' => 88, 'nameCity' => 'Sidi Taibi'],
                ['id' => 89, 'nameCity' => 'Sidi Yahya El Gharb'],
                ['id' => 90, 'nameCity' => 'Souk El Arbaa'],
                ['id' => 91, 'nameCity' => 'Akka'],
                ['id' => 92, 'nameCity' => 'Assa'],
                ['id' => 93, 'nameCity' => 'Bouizakarne'],
                ['id' => 94, 'nameCity' => 'El Ouatia'],
                ['id' => 95, 'nameCity' => 'Es-Semara'],
                ['id' => 96, 'nameCity' => 'Fam El Hisn'],
                ['id' => 97, 'nameCity' => 'Foum Zguid'],
                ['id' => 98, 'nameCity' => 'Guelmim'],
                ['id' => 99, 'nameCity' => 'Taghjijt'],
                ['id' => 100, 'nameCity' => 'Tan-Tan'],
                ['id' => 101, 'nameCity' => 'Tata'],
                ['id' => 102, 'nameCity' => 'Zag'],
                ['id' => 103, 'nameCity' => 'Marrakech'],
                ['id' => 104, 'nameCity' => 'Ait Daoud'],
                ['id' => 115, 'nameCity' => 'Amizmiz'],
                ['id' => 116, 'nameCity' => 'Assahrij'],
                ['id' => 117, 'nameCity' => 'Aït Ourir'],
                ['id' => 118, 'nameCity' => 'Ben Guerir'],
                ['id' => 119, 'nameCity' => 'Chichaoua'],
                ['id' => 120, 'nameCity' => 'El Hanchane'],
                ['id' => 121, 'nameCity' => 'El Kelaâ des Sraghna'],
                ['id' => 122, 'nameCity' => 'Essaouira'],
                ['id' => 123, 'nameCity' => 'Fraïta'],
                ['id' => 124, 'nameCity' => 'Ghmate'],
                ['id' => 125, 'nameCity' => 'Ighounane'],
                ['id' => 126, 'nameCity' => 'Imintanoute'],
                ['id' => 127, 'nameCity' => 'Kattara'],
                ['id' => 128, 'nameCity' => 'Lalla Takerkoust'],
                ['id' => 129, 'nameCity' => 'Loudaya'],
                ['id' => 130, 'nameCity' => 'Lâattaouia'],
                ['id' => 131, 'nameCity' => 'Moulay Brahim'],
                ['id' => 132, 'nameCity' => 'Mzouda'],
                ['id' => 133, 'nameCity' => 'Ounagha'],
                ['id' => 134, 'nameCity' => 'Sid LMokhtar'],
                ['id' => 135, 'nameCity' => 'Sid Zouin'],
                ['id' => 136, 'nameCity' => 'Sidi Abdallah Ghiat'],
                ['id' => 137, 'nameCity' => 'Sidi Bou Othmane'],
                ['id' => 138, 'nameCity' => 'Sidi Rahhal'],
                ['id' => 139, 'nameCity' => 'Skhour Rehamna'],
                ['id' => 140, 'nameCity' => 'Smimou'],
                ['id' => 141, 'nameCity' => 'Tafetachte'],
                ['id' => 142, 'nameCity' => 'Tahannaout'],
                ['id' => 143, 'nameCity' => 'Talmest'],
                ['id' => 144, 'nameCity' => 'Tamallalt'],
                ['id' => 145, 'nameCity' => 'Tamanar'],
                ['id' => 146, 'nameCity' => 'Tamansourt'],
                ['id' => 147, 'nameCity' => 'Tameslouht'],
                ['id' => 148, 'nameCity' => 'Tanalt'],
                ['id' => 149, 'nameCity' => 'Zeubelemok'],
                ['id' => 150, 'nameCity' => 'Meknès'],
                ['id' => 151, 'nameCity' => 'Khénifra'],
                ['id' => 152, 'nameCity' => 'Agourai'],
                ['id' => 153, 'nameCity' => 'Ain Taoujdate'],
                ['id' => 154, 'nameCity' => 'MyAliCherif'],
                ['id' => 155, 'nameCity' => 'Rissani'],
                ['id' => 156, 'nameCity' => 'Amalou Ighriben'],
                ['id' => 157, 'nameCity' => 'Aoufous'],
                ['id' => 158, 'nameCity' => 'Arfoud'],
                ['id' => 159, 'nameCity' => 'Azrou'],
                ['id' => 160, 'nameCity' => 'Aïn Jemaa'],
                ['id' => 161, 'nameCity' => 'Aïn Karma'],
                ['id' => 162, 'nameCity' => 'Aïn Leuh'],
                ['id' => 163, 'nameCity' => 'Aït Boubidmane'],
                ['id' => 164, 'nameCity' => 'Aït Ishaq'],
                ['id' => 165, 'nameCity' => 'Boudnib'],
                ['id' => 166, 'nameCity' => 'Boufakrane'],
                ['id' => 167, 'nameCity' => 'Boumia'],
                ['id' => 168, 'nameCity' => 'El Hajeb'],
                ['id' => 169, 'nameCity' => 'Elkbab'],
                ['id' => 170, 'nameCity' => 'Er-Rich'],
                ['id' => 171, 'nameCity' => 'Errachidia'],
                ['id' => 172, 'nameCity' => 'Gardmit'],
                ['id' => 173, 'nameCity' => 'Goulmima'],
                ['id' => 174, 'nameCity' => 'Gourrama'],
                ['id' => 175, 'nameCity' => 'Had Bouhssoussen'],
                ['id' => 176, 'nameCity' => 'Haj Kaddour'],
                ['id' => 177, 'nameCity' => 'Ifrane'],
                ['id' => 178, 'nameCity' => 'Itzer'],
                ['id' => 179, 'nameCity' => 'Jorf'],
                ['id' => 180, 'nameCity' => 'Kehf Nsour'],
                ['id' => 181, 'nameCity' => 'Kerrouchen'],
                ['id' => 182, 'nameCity' => 'Mhaya'],
                ['id' => 183, 'nameCity' => 'Mrirt'],
                ['id' => 184, 'nameCity' => 'Midelt'],
                ['id' => 185, 'nameCity' => 'Moulay Ali Cherif'],
                ['id' => 186, 'nameCity' => 'Moulay Bouazza'],
                ['id' => 187, 'nameCity' => 'Moulay Idriss Zerhoun'],
                ['id' => 188, 'nameCity' => 'Moussaoua'],
                ['id' => 189, 'nameCity' => 'N\'Zalat Bni Amar'],
                ['id' => 190, 'nameCity' => 'Ouaoumana'],
                ['id' => 191, 'nameCity' => 'Oued Ifrane'],
                ['id' => 192, 'nameCity' => 'Sabaa Aiyoun'],
                ['id' => 193, 'nameCity' => 'Sebt Jahjouh'],
                ['id' => 194, 'nameCity' => 'Sidi Addi'],
                ['id' => 195, 'nameCity' => 'Tichoute'],
                ['id' => 196, 'nameCity' => 'Tighassaline'],
                ['id' => 197, 'nameCity' => 'Tighza'],
                ['id' => 198, 'nameCity' => 'Timahdite'],
                ['id' => 199, 'nameCity' => 'Tinejdad'],
                ['id' => 200, 'nameCity' => 'Tizguite'],
                ['id' => 201, 'nameCity' => 'Toulal'],
                ['id' => 202, 'nameCity' => 'Tounfite'],
                ['id' => 203, 'nameCity' => 'Zaouia d\'Ifrane'],
                ['id' => 204, 'nameCity' => 'Zaïda'],
                ['id' => 205, 'nameCity' => 'Ahfir'],
                ['id' => 206, 'nameCity' => 'Aklim'],
                ['id' => 207, 'nameCity' => 'Al Aroui'],
                ['id' => 208, 'nameCity' => 'Aïn Bni Mathar'],
                ['id' => 209, 'nameCity' => 'Aïn Erreggada'],
                ['id' => 210, 'nameCity' => 'Ben Taïeb'],
                ['id' => 211, 'nameCity' => 'Berkane'],
                ['id' => 212, 'nameCity' => 'Bni Ansar'],
                ['id' => 213, 'nameCity' => 'Bni Chiker'],
                ['id' => 214, 'nameCity' => 'Bni Drar'],
                ['id' => 215, 'nameCity' => 'Bni Tadjite'],
                ['id' => 216, 'nameCity' => 'Bouanane'],
                ['id' => 217, 'nameCity' => 'Bouarfa'],
                ['id' => 218, 'nameCity' => 'Bouhdila'],
                ['id' => 219, 'nameCity' => 'Dar El Kebdani'],
                ['id' => 220, 'nameCity' => 'Debdou'],
                ['id' => 221, 'nameCity' => 'Douar Kannine'],
                ['id' => 222, 'nameCity' => 'Driouch'],
                ['id' => 223, 'nameCity' => 'El Aïoun Sidi Mellouk'],
                ['id' => 224, 'nameCity' => 'Farkhana'],
                ['id' => 225, 'nameCity' => 'Figuig'],
                ['id' => 226, 'nameCity' => 'Ihddaden'],
                ['id' => 227, 'nameCity' => 'Jaâdar'],
                ['id' => 228, 'nameCity' => 'Jerada'],
                ['id' => 229, 'nameCity' => 'Kariat Arekmane'],
                ['id' => 230, 'nameCity' => 'Kassita'],
                ['id' => 231, 'nameCity' => 'Kerouna'],
                ['id' => 232, 'nameCity' => 'Laâtamna'],
                ['id' => 233, 'nameCity' => 'Madagh'],
                ['id' => 234, 'nameCity' => 'Midar'],
                ['id' => 235, 'nameCity' => 'Nador'],
                ['id' => 236, 'nameCity' => 'Naima'],
                ['id' => 237, 'nameCity' => 'Oued Heimer'],
                ['id' => 238, 'nameCity' => 'Oujda'],
                ['id' => 239, 'nameCity' => 'Ras El Ma'],
                ['id' => 240, 'nameCity' => 'Saïdia'],
                ['id' => 241, 'nameCity' => 'Selouane'],
                ['id' => 242, 'nameCity' => 'Sidi Boubker'],
                ['id' => 243, 'nameCity' => 'Sidi Slimane Echcharaa'],
                ['id' => 244, 'nameCity' => 'Talsint'],
                ['id' => 245, 'nameCity' => 'Taourirt'],
                ['id' => 246, 'nameCity' => 'Tendrara'],
                ['id' => 247, 'nameCity' => 'Tiztoutine'],
                ['id' => 248, 'nameCity' => 'Touima'],
                ['id' => 249, 'nameCity' => 'Touissit'],
                ['id' => 250, 'nameCity' => 'Zaïo'],
                ['id' => 251, 'nameCity' => 'Zeghanghane'],
                ['id' => 252, 'nameCity' => 'Rabat'],
                ['id' => 253, 'nameCity' => 'Salé'],
                ['id' => 254, 'nameCity' => 'Ain El Aouda'],
                ['id' => 255, 'nameCity' => 'Harhoura'],
                ['id' => 256, 'nameCity' => 'Khémisset'],
                ['id' => 257, 'nameCity' => 'Oulmès'],
                ['id' => 258, 'nameCity' => 'Rommani'],
                ['id' => 259, 'nameCity' => 'Sidi Allal El Bahraoui'],
                ['id' => 260, 'nameCity' => 'Sidi Bouknadel'],
                ['id' => 261, 'nameCity' => 'Skhirate'],
                ['id' => 262, 'nameCity' => 'Tamesna'],
                ['id' => 263, 'nameCity' => 'Témara'],
                ['id' => 264, 'nameCity' => 'Tiddas'],
                ['id' => 265, 'nameCity' => 'Tiflet'],
                ['id' => 266, 'nameCity' => 'Touarga'],
                ['id' => 267, 'nameCity' => 'Agadir'],
                ['id' => 268, 'nameCity' => 'Agdz'],
                ['id' => 269, 'nameCity' => 'Agni Izimmer'],
                ['id' => 270, 'nameCity' => 'Aït Melloul'],
                ['id' => 271, 'nameCity' => 'Alnif'],
                ['id' => 272, 'nameCity' => 'Anzi'],
                ['id' => 273, 'nameCity' => 'Aoulouz'],
                ['id' => 274, 'nameCity' => 'Aourir'],
                ['id' => 275, 'nameCity' => 'Arazane'],
                ['id' => 276, 'nameCity' => 'Aït Baha'],
                ['id' => 277, 'nameCity' => 'Aït Iaâza'],
                ['id' => 278, 'nameCity' => 'Aït Yalla'],
                ['id' => 279, 'nameCity' => 'Ben Sergao'],
                ['id' => 280, 'nameCity' => 'Biougra'],
                ['id' => 281, 'nameCity' => 'Boumalne-Dadès'],
                ['id' => 282, 'nameCity' => 'Dcheira El Jihadia'],
                ['id' => 283, 'nameCity' => 'Drargua'],
                ['id' => 284, 'nameCity' => 'El Guerdane'],
                ['id' => 285, 'nameCity' => 'Harte Lyamine'],
                ['id' => 286, 'nameCity' => 'Ida Ougnidif'],
                ['id' => 287, 'nameCity' => 'Ifri'],
                ['id' => 288, 'nameCity' => 'Igdamen'],
                ['id' => 289, 'nameCity' => 'Ighil n\'Oumgoun'],
                ['id' => 290, 'nameCity' => 'Imassine'],
                ['id' => 291, 'nameCity' => 'Inezgane'],
                ['id' => 292, 'nameCity' => 'Irherm'],
                ['id' => 293, 'nameCity' => 'Kelaat-M\'Gouna'],
                ['id' => 294, 'nameCity' => 'Lakhsas'],
                ['id' => 295, 'nameCity' => 'Lakhsass'],
                ['id' => 296, 'nameCity' => 'Lqliâa'],
                ['id' => 297, 'nameCity' => 'M\'semrir'],
                ['id' => 298, 'nameCity' => 'Massa (Ma)'],
                ['id' => 299, 'nameCity' => 'Megousse'],
                ['id' => 300, 'nameCity' => 'Ouarzazate'],
                ['id' => 301, 'nameCity' => 'Oulad Berhil'],
                ['id' => 302, 'nameCity' => 'Oulad Teïma'],
                ['id' => 303, 'nameCity' => 'Sarghine'],
                ['id' => 304, 'nameCity' => 'Sidi Ifni'],
                ['id' => 305, 'nameCity' => 'Skoura'],
                ['id' => 306, 'nameCity' => 'Tabounte'],
                ['id' => 307, 'nameCity' => 'Tafraout'],
                ['id' => 308, 'nameCity' => 'Taghzout'],
                ['id' => 309, 'nameCity' => 'Tagzen'],
                ['id' => 310, 'nameCity' => 'Taliouine'],
                ['id' => 311, 'nameCity' => 'Tamegroute'],
                ['id' => 312, 'nameCity' => 'Tamraght'],
                ['id' => 313, 'nameCity' => 'Tanoumrite Nkob Zagora'],
                ['id' => 314, 'nameCity' => 'Taourirt ait zaghar'],
                ['id' => 315, 'nameCity' => 'Taroudannt'],
                ['id' => 316, 'nameCity' => 'Temsia'],
                ['id' => 317, 'nameCity' => 'Tifnit'],
                ['id' => 318, 'nameCity' => 'Tisgdal'],
                ['id' => 319, 'nameCity' => 'Tiznit'],
                ['id' => 320, 'nameCity' => 'Toundoute'],
                ['id' => 321, 'nameCity' => 'Zagora'],
                ['id' => 322, 'nameCity' => 'Afourar'],
                ['id' => 323, 'nameCity' => 'Aghbala'],
                ['id' => 324, 'nameCity' => 'Azilal'],
                ['id' => 325, 'nameCity' => 'Aït Majden'],
                ['id' => 326, 'nameCity' => 'Beni Ayat'],
                ['id' => 327, 'nameCity' => 'Béni Mellal'],
                ['id' => 328, 'nameCity' => 'Bin elouidane'],
                ['id' => 329, 'nameCity' => 'Bradia'],
                ['id' => 330, 'nameCity' => 'Bzou'],
                ['id' => 331, 'nameCity' => 'Dar Oulad Zidouh'],
                ['id' => 332, 'nameCity' => 'Demnate'],
                ['id' => 333, 'nameCity' => 'Dra\'a'],
                ['id' => 334, 'nameCity' => 'El Ksiba'],
                ['id' => 335, 'nameCity' => 'Foum Jamaa'],
                ['id' => 336, 'nameCity' => 'Fquih Ben Salah'],
                ['id' => 337, 'nameCity' => 'Kasba Tadla'],
                ['id' => 338, 'nameCity' => 'Ouaouizeght'],
                ['id' => 339, 'nameCity' => 'Oulad Ayad'],
                ['id' => 340, 'nameCity' => 'Oulad M\'Barek'],
                ['id' => 341, 'nameCity' => 'Oulad Yaich'],
                ['id' => 342, 'nameCity' => 'Sidi Jaber'],
                ['id' => 343, 'nameCity' => 'Souk Sebt Oulad Nemma'],
                ['id' => 344, 'nameCity' => 'Zaouïat Cheikh'],
                ['id' => 345, 'nameCity' => 'Tanger'],
                ['id' => 346, 'nameCity' => 'Tétouan'],
                ['id' => 347, 'nameCity' => 'Akchour'],
                ['id' => 348, 'nameCity' => 'Assilah'],
                ['id' => 349, 'nameCity' => 'Bab Berred'],
                ['id' => 350, 'nameCity' => 'Bab Taza'],
                ['id' => 351, 'nameCity' => 'Brikcha'],
                ['id' => 352, 'nameCity' => 'Chefchaouen'],
                ['id' => 353, 'nameCity' => 'Dar Bni Karrich'],
                ['id' => 354, 'nameCity' => 'Dar Chaoui'],
                ['id' => 355, 'nameCity' => 'Fnideq'],
                ['id' => 356, 'nameCity' => 'Gueznaia'],
                ['id' => 357, 'nameCity' => 'Jebha'],
                ['id' => 358, 'nameCity' => 'Karia'],
                ['id' => 359, 'nameCity' => 'Khémis Sahel'],
                ['id' => 360, 'nameCity' => 'Ksar El Kébir'],
                ['id' => 361, 'nameCity' => 'Larache'],
                ['id' => 362, 'nameCity' => 'M\'diq'],
                ['id' => 363, 'nameCity' => 'Martil'],
                ['id' => 364, 'nameCity' => 'Moqrisset'],
                ['id' => 365, 'nameCity' => 'Oued Laou'],
                ['id' => 366, 'nameCity' => 'Oued Rmel'],
                ['id' => 367, 'nameCity' => 'Ouazzane'],
                ['id' => 368, 'nameCity' => 'Point Cires'],
                ['id' => 369, 'nameCity' => 'Sidi Lyamani'],
                ['id' => 370, 'nameCity' => 'Sidi Mohamed ben Abdallah el-Raisuni'],
                ['id' => 371, 'nameCity' => 'Zinat'],
                ['id' => 372, 'nameCity' => 'Ajdir'],
                ['id' => 373, 'nameCity' => 'Aknoul'],
                ['id' => 374, 'nameCity' => 'Al Hoceïma'],
                ['id' => 375, 'nameCity' => 'Aït Hichem'],
                ['id' => 376, 'nameCity' => 'Bni Bouayach'],
                ['id' => 377, 'nameCity' => 'Bni Hadifa'],
                ['id' => 378, 'nameCity' => 'Ghafsai'],
                ['id' => 379, 'nameCity' => 'Guercif'],
                ['id' => 380, 'nameCity' => 'Imzouren'],
                ['id' => 381, 'nameCity' => 'Inahnahen'],
                ['id' => 382, 'nameCity' => 'Issaguen (Ket)'],
                ['id' => 383, 'nameCity' => 'Karia (El Jad)'],
                ['id' => 384, 'nameCity' => 'Karia Ba Mohamed'],
                ['id' => 385, 'nameCity' => 'Oued Amlil'],
                ['id' => 386, 'nameCity' => 'Oulad Zbair'],
                ['id' => 387, 'nameCity' => 'Tahla'],
                ['id' => 388, 'nameCity' => 'Tala Tazegwaght'],
                ['id' => 389, 'nameCity' => 'Tamassint'],
                ['id' => 390, 'nameCity' => 'Taounate'],
                ['id' => 391, 'nameCity' => 'Targuist'],
                ['id' => 392, 'nameCity' => 'Taza'],
                ['id' => 393, 'nameCity' => 'Taïnaste'],
                ['id' => 394, 'nameCity' => 'Thar Es-Souk'],
                ['id' => 395, 'nameCity' => 'Tissa'],
                ['id' => 396, 'nameCity' => 'Tizi Ouasli'],
                ['id' => 397, 'nameCity' => 'Laayoune,'],
                ['id' => 398, 'nameCity' => 'El Marsa'],
                ['id' => 399, 'nameCity' => 'Tarfaya'],
                ['id' => 400, 'nameCity' => 'Boujdour'],
                ['id' => 401, 'nameCity' => 'Awsard'],
                ['id' => 402, 'nameCity' => 'Oued-Eddahab'],
                ['id' => 403, 'nameCity' => 'Stehat'],
                ['id' => 404, 'nameCity' => 'Aït Attab'],
                                
        ]);
    }
}
